apiVersion: v1
kind: ConfigMap
metadata:
  name: student-configmap
data:
  db_host: mysql8:3306
  db_username: root
  db_password: "1234567"
  db_name: java-kubernetes-db
  db_port: "3306"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: course-configmap
data:
  db_host: postgresql14:5432
  db_username: postgres
  db_password: "1234567"
  db_name: java-kubernetes-db-course
  db_port: "5432"
  student_url: student-service

