version: "3.9"

networks: #Optional
  network1:
    name: network1

volumes:
  mysqlDB:
    name: mysqlDB
  pgdataDB:
    name: pgdataDB

services:


  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: java-kubernetes-db
    volumes:
      - mysqlDB:/var/lib/mysql
    restart: always
    networks:
      - network1


  postgresql14:
    container_name: postgresql14
    image: postgres:15.3-alpine3.18
    ports:
      - "5532:5432"
    networks:
      - network1
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: java-kubernetes-db-course
    volumes:
      - pgdataDB:/var/lib/postgresql/data
    restart: always


  student-service:
    container_name: student-service
    image: student
    ports:
      - "8001:8001"
    env_file:
      - ./student-service/env
    networks:
      - network1
    depends_on:
      - mysql8
    restart: always


  course-service:
    container_name: course-service
    image: course
    ports:
      - "8002:8002"
    env_file:
      - ./Course/env
    networks:
      - network1
    depends_on:
      - postgresql14
    restart: always