version: "3.9"

networks: #Optional
  network1:
    name: network1

volumes:
  mysqlDB:
    name: mysqlDB
  pgdataDB:
    name: pgdataDB

services:


  mysql8:
    container_name: mysql8
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234567
      MYSQL_DATABASE: java-kubernetes-db
    volumes:
      - mysqlDB:/var/lib/mysql
    restart: always
    networks:
      - network1


  postgresql14:
    container_name: postgresql14
    image: postgres:15.3-alpine3.18
    ports:
      - "5532:5432"
    networks:
      - network1
    environment:
      POSTGRES_PASSWORD: 1234567
      POSTGRES_DB: java-kubernetes-db-course
    volumes:
      - pgdataDB:/var/lib/postgresql/data
    restart: always


  student-service:
    image: fideljose17/student-service
#    container_name: student-service
    build:
      context: ./
      dockerfile: ./student-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      PORT: 8001
      DB_HOST: mysql8:3306
      DB_USERNAME: root
      DB_PASSWORD: 1234567
      DB_NAME: java-kubernetes-db
#    env_file:
#      - ./student-service/env
    networks:
      - network1
    depends_on:
      - mysql8
    restart: always


  course-service:
    image: fideljose17/course-service
#    container_name: course-service
    build:
      context: ./
      dockerfile: ./Course/Dockerfile
    ports:
      - "8002:8002"
    environment:
      PORT: 8002
      DB_HOST: postgresql14:5432
      DB_NAME: java-kubernetes-db-course
      DB_USERNAME: postgres
      DB_PASSWORD: 1234567
      STUDENTS_URL: ec2-54-221-111-33.compute-1.amazonaws.com
#    env_file:
#      - ./Course/env
    networks:
      - network1
    depends_on:
      - postgresql14
      - student-service
    restart: always

