apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  volumeName: mysql-pv # name persistence volume
  accessModes:
    - ReadWriteOnce
  storageClassName: standard #kubectl get sc (Storage Class)
  resources:
    requests:
      storage: 1Gi