apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgresql-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: standard #kubectl get sc (Storage Class)
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /any-directory/var/lib/postgresql/data
    type: DirectoryOrCreate