spring:
  cloud:
    gateway:
      routes:
        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**
          filters:
            - StripPrefix=2 # api and courses = 2 Prefix
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/students/**
          filters:
            - StripPrefix=2 # api and students = 2 Prefix
        - id: default_route
          uri: https://google.com
          predicates:
            - Path=/**